name: Daily Cybersecurity Contributions

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allow manual execution

jobs:
  contribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master  # Use master branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Cybersecurity Contribution Script
      run: python cyber_contribute.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "Automated cybersecurity contribution update" || echo "No changes to commit"
        git push origin master  # Push to master branch
